version: '3.3'

services:
  redis:
    image: redis:latest
    networks:
      - nextbot-net
    container_name: redis
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - nextbot_redis:/data
    ports:
      - 6379:6379

volumes:
  nextbot_redis:


networks:
  nextbot-net:
    name: nextbot-net
    driver: bridge
