services:
  api:
    container_name: nextbot_api
    image: evolution/api:local
    build: .
    restart: always
    ports:
      - 8080:8080
    volumes:
      - nextbot_instances:/nextbot/instances
    networks:
      - nextbot-net
    env_file:
      - .env
    expose:
      - 8080

volumes:
  nextbot_instances:


networks:
  nextbot-net:
    name: nextbot-net
    driver: bridge
