version: '3.9'

services:
  postgres:
    image: postgres:13
    container_name: evolution_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: evolution
    volumes:
      - evolution_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    container_name: evolution_redis
    restart: always
    ports:
      - "6379:6379"

  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api:v2.1.1
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://postgres:postgres@postgres:5432/evolution
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://redis:6379/1
      - AUTHENTICATION_API_KEY=${AUTHENTICATION_API_KEY}
    depends_on:
      - postgres
      - redis
    volumes:
      - evolution_instances:/evolution/instances

volumes:
  evolution_pgdata:
  evolution_instances: